Cargo Stylus Factory
OffchainLabs/nitro-contracts pull request #240
Opened 2024-08-26 14:48 UTC by chrisco512

Draft for a Stylus factory contract that may be used by the `cargo stylus` CLI tool to deploy, activate, and run an arbitrary constructor in a single transaction.

In Stylus/WASM context we are unable to run Rust or WASM code during the deployment step. There is also a need to activate WASM programs, which is currently abstracted from users via the `cargo stylus` tool. Users can currently define in their Rust code an "init" method but it must be called after activation and there is a need to gate the function manually to a specific deployer address as well as add arbitrary state variables to gate other methods from being invoked before the contract is initialized. 

This contract enables a better developer experience. The intention is to deterministically deploy this contract using create2 on Arbitrum chains so that Cargo Stylus can use it to deploy. The Stylus SDK will add a future `#[constructor]` proc macro that will gate a defined method to being invoked by this contract alone during the deployment transaction.

2024-08-27 10:01 UTC, gzeoneth requested changes

2024-08-27 10:01 UTC, gzeoneth commented on src/stylus/CargoStylusFactory.sol
> +contract CargoStylusFactory {
missing a payable receive function to receive refund from constructor (if any)

2024-08-27 10:01 UTC, gzeoneth commented on src/stylus/CargoStylusFactory.sol
> +        uint256 excessValue = msg.value - _activationFee - _constructorValue;
can simply refund `address(this).balance`

2024-08-27 10:01 UTC, gzeoneth commented on src/stylus/CargoStylusFactory.sol
> +    function initializeContract(
if we were to consolidate the 2 public function, we might as well inline these instead of making internal functions

2024-08-27 10:28 UTC, gzeoneth commented on src/stylus/CargoStylusFactory.sol
> +        refundExcessValue(activationFee, _constructorValue);
this ignore any refund from the constructor call (if any), I think we can wrap a balance check before and after the call to constructor to know the net amount spent in the constructor and do refund appropriately

there is also an additional edge case where the constructor cost is negative (if it somehow received more fund from the constructor)

2024-12-18 17:22 UTC, gzeoneth commented
while there were some comment regarding constructor refund, maybe we can assume it will never happen like other CREATE2 factories

2024-12-18 17:23 UTC, gzeoneth commented on src/stylus/CargoStylusFactory.sol
> +contract CargoStylusFactory {
specifically, I mean if `dataFee < _activationValue` in
```
(, uint256 dataFee) = IArbWasm(ARB_WASM).activateProgram{value: _activationValue}(
            _contract
        );
```
I am not sure if that refund involves evm call tho

2025-01-03 15:51 UTC, gligneul commented on src/stylus/CargoStylusFactory.sol
> +        emit ContractActivated(_contract);
I'm getting this error if the program was previously activated:
```
    (code: 3, message: execution reverted: error ProgramUpToDate(), data: Some(String("0xcc944bf2")))
```

2025-02-04 16:07 UTC, godzillaba commented
replaced by #294

2025-02-04 16:07 UTC, closed without merging