Add upgrade executor to rollup creation flow
OffchainLabs/nitro-contracts pull request #49
Opened 2023-08-03 11:58 UTC by gvladika

Each call to `createRollup` will create UpgradeExecutor. Executor will be owner of proxyAdmin which owns non-rollup bridge contracts - bridge, seqInbox, inbox, rollupEventInbox, outbox, challengeManager. RollupOwner is the single account that has `executor` role on the UpgradeExecutor.

2023-08-03 12:30 UTC, gzeoneth requested changes

2023-08-03 12:57 UTC, gzeoneth commented on src/rollup/RollupCreator.sol
> +        upgradeExecutor.initialize(address(upgradeExecutor), upgradeExecutors);
let's call this executors for less confusion
```suggestion
        address[] memory executors = new address[](1);
        executors[0] = config.owner;
        upgradeExecutor.initialize(address(upgradeExecutor), executors);
```

2023-08-03 12:57 UTC, gzeoneth commented on src/libraries/UpgradeExecutor.sol
Wonder if this should live here or the gov repo, I think it make sense to live here to avoid circular dependency of 2 packages tho we need to make sure the correct OZ version is used. This contract is audited with OZ 4.7.2 in gov but `nitro-contracts` repo is using 4.5.0/4.5.2

2023-08-03 13:02 UTC, gzeoneth commented on src/libraries/UpgradeExecutor.sol
I see little risk in this specific instance but we should still align the version just in case

2023-08-03 15:32 UTC, gvladika commented on src/libraries/UpgradeExecutor.sol
A lot of contracts in this repo are using OZ, so if we changed version now it would be big impact. Shall we simply re-audit this version of UpgradeExecutor? Audit will happen soon anyways

2023-08-08 21:01 UTC, gzeoneth commented
pushed a few commit to use the upgrade-executor npm package, kinda tricky because typechain does not include a typesafe deploy function so we cannot use the UpgradeExecutor__factory directly; instead I am using the abi and bytecode to create a factory manually https://github.com/OffchainLabs/nitro-contracts/pull/49/commits/ca401d12769fe5a18e87ebe5d0c2f3b403be0c0e

2023-08-25 13:12 UTC, gvladika commented on src/libraries/UpgradeExecutor.sol
Now using latest release of upgrade-executor npm package

2023-08-28 10:58 UTC, gzeoneth approved these changes

2023-08-28 11:04 UTC, merged